import Head from 'next/head'
import Image from 'next/image'
import {useQuery, gql} from '@apollo/client'
import styles from '../styles/Home.module.css'

const GET_POST=  gql `{
getBlogs {
    author
    body
    created_at
    id
    title
  }
}
`

export default function Home() {
  console.log("url",process.env.NEXT_STEPZEN_API_KEY)
  const {data, loading, error}= useQuery(GET_POST)
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

</main>
    </div>
  )
}
